name: flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  fonts:
    - family: KingredModern
      fonts:
        - asset: assets/fonts/kingred.otf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf

  uses-material-design: true

